### ISSUE TITLE
WeakSet and WeakMap bug

### ISSUE THREAD

**Issue by BridgeAR** [shouldjs/equal#4]
Right now WeakSet and WeakMap are considered to behave the same as Set and Map. This is however not true and comparing these types will result in the following error. It is actually not possible to check for WeakSet or WeakMap equality at all. It is only possible to check if a entry itself exists or not.
```js
const a = new WeakSet()
const b = new WeakSet()
eq(a,b) // TypeError: a.entries is not a function
    at EQ._check_object_weak-set (/home/repos/general/equal/cjs/should-equal.js:281:23)
    at EQ.check0 (/home/repos/general/equal/cjs/should-equal.js:130:7)
    at EQ.check (/home/repos/general/equal/cjs/should-equal.js:90:12)
    at eq (/home/repos/general/equal/cjs/should-equal.js:312:29)
```

**Comment by btd** [comment]
Yep 👍 thanks. I used usual methods like has, set, get but when implementing in some reason i decide it should have the same methods like Map. 
Do you think it is right just return false for WeakMap/Set?

**Comment by BridgeAR** [comment]
Comparing two WeakSets should return true out of my perspective if all checks besides the value check say they are equal.

**Comment by btd** [comment]
Closing this as i used ref checks in 2.0.0
