### ISSUE TITLE
Bug in Map with object keys

### ISSUE THREAD

**Issue by BridgeAR** [shouldjs/equal#5]
In Maps it is possible to use objects as keys and even to use the same key multiple times.
The latter will fail right now.
```js
const a = new Map([[{}, {a:6}], [{}, {a:5}]])
const b = new Map([[{}, {a:6}], [{}, {a:5}]])
eq(a, b) // failure
```
```
[ EqualityFail {
    a: 6,
    b: 5,
    reason: 'A is not equal to B',
    path: [ 'a' ],
    showReason: false },
  EqualityFail {
    a: 5,
    b: 6,
    reason: 'A is not equal to B',
    path: [ 'a' ],
    showReason: false } ]
```

**Comment by btd** [comment]
Yep, agree, as Map preserve order need to do ordered check.

**Comment by BridgeAR** [comment]
Actually, I think Map and Set should always be considered unordered. This is also already the case for e.g.
```js
const a = new Map([[1,1], [2, 1]])
const b = new Map([[2,1], [1, 1]])
eq(a, b) // true
```
Comparing unordered object keys is more complex though (ideally O(n log n) and with a simple implementation O(n^2)).

**Comment by btd** [comment]
Yep, actually makes sense, so need just maintain Map behaviour is key the same use latest always.

**Comment by btd** [comment]
Just thinking a bit more i stucked, i am trying to do there value comparison, but this is different references - and different keys. Need to think a bit more.
